[package]
name = "rust-hello-world"
version = "0.1.0"
authors = ["Nikolai Spasov <ns@codingrobot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
